Error on line 6: wrong number of parameters in call: x.f(1, 2)
    Note: 1 expected, 2 given
